---
title: "Problem Set: Explore One Variable"
output: html_document
---

```{r setup, include=TRUE}

library(ggplot2)
data(diamonds)

```



```{r explore, include=TRUE}

# Quiz #1: Data set dimensions and structure
dim(diamonds)
str(diamonds)

# Quiz #2: Histogram
ggplot(data = diamonds, aes(x = price)) +
  geom_histogram()

# Quiz #3: Summary statistics
summary(diamonds)

# Quiz #4: Subsetting
dim(subset(diamonds, price < 500))
dim(subset(diamonds, price < 250))
dim(subset(diamonds, price >= 15000))
# OR
dim(diamonds[diamonds$price < 500,])


# Quiz #5: Scales
ggplot(data = diamonds, aes(x = price)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(limits = c(0,2000), breaks = seq(0,2000,100))

```

### Key Point: Use geom_histogram() for continuous variables and geom_bar() for discrete variables)

```{r, include=TRUE}

# Quiz #6: Faceting
ggplot(data = diamonds, aes(x = price)) +
  geom_histogram() +
#  scale_x_continuous() +
  facet_wrap(~cut)

# Quiz #7: "by"
by(diamonds$price, diamonds$cut, summary)

# Quiz #8: Free scales
ggplot(data = diamonds, aes(x = price)) +
  geom_histogram() +
#  scale_x_continuous() +
  facet_wrap(~cut, scales="free")

# Quiz #9: Logarithmic scales
ggplot(data = subset(diamonds, !is.na(carat)), aes(x = price/carat)) +
  geom_histogram() +
  scale_x_log10() +
#  scale_x_continuous() +
  facet_wrap(~cut, scales="free")

# Quiz #10: Box plots
ggplot(data = diamonds, aes(x = color, y = price)) +
  geom_boxplot() +
  ggtitle('Diamond price ranges for different colors') +
  theme(plot.title = element_text(hjust = 0.5))

# Quiz #11
by(diamonds$price, diamonds$color, summary)

# Quiz 12: Labeling
ggplot(data = diamonds, aes(x = color, y = price/carat)) +
  geom_boxplot() +
  ggtitle('Diamond price ranges for different colors') +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab('Color') +
  ylab('Price per carat ($)')

# Quiz 13: Frequency polygon
ggplot(data = diamonds, aes(x = carat)) +
  geom_freqpoly(binwidth = 0.01) +
  scale_x_continuous(breaks = seq(0,5,.2))







```

